# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce1705a3267fd7e059b1456d716b759bb6f505897aa4230f06babe4a83b07e45d67e00c99e6b1365b78ab04c2f3ed3c7c739a2478de72b1203afdf0a9aa1fad3

test:
  secret_key_base: f6c99db515f71557699bd347bee07fa4149cb16dacd2d30292a7f6d539758200d4a34a22d7ecd48f640ff490c5cac6a3cb41f0ddf4e612bf6d6d28f680e9e93b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
